name: Deliver Tokens To Consumer

on:
  push:
    paths:	
      - 'input/tokens.json'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: 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
        # This is the branch that has the code for this article
        src_branch: main
        src_path: output/scss/_variables.scss
        dst_owner: jptrinh
        dst_repo_name: style-dictionary
        dst_branch: main
        dst_path: tokens/_variables.scss
        username: jptrinh
        email: jpvh.trinh@gmail.com
        commit_message: Update platform deliverable
